version: '3'
services:
  piseth:
    #image: it for name your image after docker build -t nameyourimages .
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3205:3000
   
 	