version: '3'
services:
  ecommerce_by_piseth:
    #	  image: naemyouimages
    container_name: ecommerce_by_piseth
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3206:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - data_analytics
networks:
  data_analytics:
    external: true
